name: Find-A-Coach Frontend CI to DockerHub

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

jobs:
  front_end_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend-vue3
          file: ./frontend-vue3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/find-a-coach-frontend:latest
